import type { Idioma } from "@/lib/i18n/idiomas";
// Dicionário do módulo: integração não modifica o dicionário compartilhado.
const pt = {
  sendInvitation: "Enviar convite na conversa",
  sentInvitation: "Convite enviado",
  invalidSurvey: "Informe o ID da conversa e uma validade entre 1 e 720 horas.",
  historyLimited:
    "Exibindo as 100 solicitações mais recentes. As métricas consideram todo o histórico destas conversas.",
  title: "Qualidade do atendimento",
  intro:
    "Metas de resposta e resolução nas conversas existentes. Nenhuma mensagem é enviada automaticamente.",
  clock:
    "Tempo corrido, inclusive noites, fins de semana e pausas. Não há calendário comercial nem suspensão do relógio.",
  policy: "Metas da organização",
  enabled: "Ativar metas",
  firstTarget: "Primeira resposta (minutos)",
  resolutionTarget: "Resolução (minutos)",
  optional: "Deixe vazio para não medir esta meta.",
  save: "Salvar metas",
  loading: "Carregando…",
  reload: "Atualizar",
  error: "Não foi possível concluir. Tente novamente.",
  invalid: "Informe pelo menos uma meta positiva ao ativar.",
  disabled: "Metas desativadas. Configure os prazos que sua organização escolheu.",
  pageScope: "Métricas das conversas nesta página",
  response: "Primeira resposta enviada",
  resolution: "Resolução confirmada",
  unresolved: "Encerradas sem resolução confirmada",
  csat: "Satisfação (1–5)",
  samples: "Amostras",
  noData: "Sem dados",
  alerts: "Conversas que precisam de atenção",
  empty: "Nenhum atendimento disponível.",
  noAlerts: "Nenhum alerta nesta página.",
  inbox: "Abrir conversa",
  conversations: "Atendimentos",
  next: "Próxima página",
  previous: "Página anterior",
  state: "Estado",
  status: "Status da conversa",
  unconfigured: "Sem meta",
  not_started: "Aguardando mensagem recebida",
  pending: "Dentro do prazo, em andamento",
  met: "Meta atendida",
  breached: "Prazo excedido",
  ended: "Encerrada sem resolução",
  unknown: "Sem registro de encerramento",
  elapsed: "Decorrido",
  target: "Meta",
  survey: "Pesquisa de satisfação",
  conversationId: "ID da conversa",
  expiry: "Validade do link (horas, de 1 a 720)",
  create: "Criar link",
  copy: "Copiar convite",
  copied: "Convite copiado",
  copyError: "Não foi possível copiar. Selecione o texto e copie.",
  linkHelp:
    "Copie o convite e envie pela conversa somente se decidir solicitar a avaliação. Criar o link não envia mensagens.",
  invitation: "Como foi seu atendimento? Se quiser, avalie de 1 a 5 neste link:",
  expires: "Expira em",
  feedback: "Avaliações recebidas",
  noFeedback: "Ainda não há avaliação recebida.",
  lowScores: "Notas 1–2",
  comment: "Comentário (opcional)",
  feedbackTitle: "Como foi seu atendimento?",
  feedbackIntro: "Escolha uma nota de 1 a 5. Seu comentário é opcional.",
  score: "Nota",
  submit: "Enviar avaliação",
  thanks: "Obrigado! Sua avaliação foi registrada.",
  unavailable: "Este link expirou, já foi utilizado ou não está disponível.",
  slow: "Muitas tentativas. Aguarde um minuto e tente novamente.",
  veryBad: "Muito ruim",
  veryGood: "Muito bom",
  seconds: "s",
  minutes: "min",
  hours: "h",
  saved: "Metas salvas",
  readonly: "Somente gerente ou administrador pode alterar metas e criar links.",
  open: "Aberta",
  claimed: "Em atendimento",
  closed: "Encerrada",
  resolved: "Resolvida",
  archived: "Arquivada",
  snoozed: "Adiada",
  awaiting_human: "Aguardando humano",
  awaiting_lead: "Aguardando cliente",
  surveyUsage: "Uso único. A nota fica vinculada à conversa.",
  received: "Recebida em",
  pendingSurveys: "Links aguardando avaliação",
  expiredSurveys: "Links expirados sem avaliação",
  expired: "Expirado",
  waiting: "Aguardando avaliação",
  responseDefinition:
    "A primeira resposta conta mensagens enviadas por humano ou assistente; não comprova que o problema foi resolvido.",
  resolutionDefinition:
    "Somente o status resolvida conta como resolução. Encerrada e arquivada são mostradas separadamente.",
};
const es: typeof pt = {
  sendInvitation: "Enviar invitación en la conversación",
  sentInvitation: "Invitación enviada",
  invalidSurvey: "Ingrese el ID de la conversación y una validez entre 1 y 720 horas.",
  historyLimited:
    "Se muestran las 100 solicitudes más recientes. Las métricas consideran todo el historial de estas conversaciones.",
  title: "Calidad de la atención",
  intro:
    "Metas de respuesta y resolución en las conversaciones existentes. Ningún mensaje se envía automáticamente.",
  clock:
    "Tiempo transcurrido, incluidas noches, fines de semana y pausas. No hay calendario laboral ni suspensión del reloj.",
  policy: "Metas de la organización",
  enabled: "Activar metas",
  firstTarget: "Primera respuesta (minutos)",
  resolutionTarget: "Resolución (minutos)",
  optional: "Deje vacío para no medir esta meta.",
  save: "Guardar metas",
  loading: "Cargando…",
  reload: "Actualizar",
  error: "No se pudo completar. Inténtelo de nuevo.",
  invalid: "Ingrese al menos una meta positiva al activar.",
  disabled: "Metas desactivadas. Configure los plazos elegidos por su organización.",
  pageScope: "Métricas de las conversaciones en esta página",
  response: "Primera respuesta enviada",
  resolution: "Resolución confirmada",
  unresolved: "Cerradas sin resolución confirmada",
  csat: "Satisfacción (1–5)",
  samples: "Muestras",
  noData: "Sin datos",
  alerts: "Conversaciones que necesitan atención",
  empty: "No hay atenciones disponibles.",
  noAlerts: "No hay alertas en esta página.",
  inbox: "Abrir conversación",
  conversations: "Atenciones",
  next: "Página siguiente",
  previous: "Página anterior",
  state: "Estado",
  status: "Estado de la conversación",
  unconfigured: "Sin meta",
  not_started: "Esperando mensaje recibido",
  pending: "Dentro del plazo, en curso",
  met: "Meta cumplida",
  breached: "Plazo excedido",
  ended: "Cerrada sin resolución",
  unknown: "Sin registro de cierre",
  elapsed: "Transcurrido",
  target: "Meta",
  survey: "Encuesta de satisfacción",
  conversationId: "ID de la conversación",
  expiry: "Validez del enlace (horas, de 1 a 720)",
  create: "Crear enlace",
  copy: "Copiar invitación",
  copied: "Invitación copiada",
  copyError: "No se pudo copiar. Seleccione el texto y cópielo.",
  linkHelp:
    "Copie la invitación y envíela por la conversación solo si decide solicitar la evaluación. Crear el enlace no envía mensajes.",
  invitation: "¿Cómo fue su atención? Si lo desea, evalúela de 1 a 5 en este enlace:",
  expires: "Vence el",
  feedback: "Evaluaciones recibidas",
  noFeedback: "Todavía no hay evaluaciones recibidas.",
  lowScores: "Notas 1–2",
  comment: "Comentario (opcional)",
  feedbackTitle: "¿Cómo fue su atención?",
  feedbackIntro: "Elija una nota de 1 a 5. Su comentario es opcional.",
  score: "Nota",
  submit: "Enviar evaluación",
  thanks: "¡Gracias! Su evaluación fue registrada.",
  unavailable: "Este enlace venció, ya fue utilizado o no está disponible.",
  slow: "Demasiados intentos. Espere un minuto e inténtelo de nuevo.",
  veryBad: "Muy mala",
  veryGood: "Muy buena",
  seconds: "s",
  minutes: "min",
  hours: "h",
  saved: "Metas guardadas",
  readonly: "Solo un gerente o administrador puede cambiar metas y crear enlaces.",
  open: "Abierta",
  claimed: "En atención",
  closed: "Cerrada",
  resolved: "Resuelta",
  archived: "Archivada",
  snoozed: "Pospuesta",
  awaiting_human: "Esperando humano",
  awaiting_lead: "Esperando cliente",
  surveyUsage: "Uso único. La nota queda vinculada a la conversación.",
  received: "Recibida el",
  pendingSurveys: "Enlaces pendientes de evaluación",
  expiredSurveys: "Enlaces vencidos sin evaluación",
  expired: "Vencido",
  waiting: "Esperando evaluación",
  responseDefinition:
    "La primera respuesta cuenta mensajes enviados por una persona o asistente; no demuestra que el problema fue resuelto.",
  resolutionDefinition:
    "Solo el estado resuelta cuenta como resolución. Cerrada y archivada se muestran por separado.",
};
export function qualityText(idioma: Idioma) {
  return idioma === "es" ? es : pt;
}
export type QualityText = typeof pt;
